### ISSUE TITLE
Immortals can't contain properties

### ISSUE THREAD

**Issue by cimryan** [microsoft/AMBROSIA#105]
Immortals can't contain properties because of a bug in CopyFromDeserializedImmortal.

The function gets a "MemberTypes.Property", and then immediately tries to cast it to a (FieldInfo).

if (memberInfo.MemberType == MemberTypes.Field || memberInfo.MemberType == MemberTypes.Property)
                {
                    var fi = (FieldInfo)memberInfo;
                    var v = fi.GetValue(otherImmortal);
                    fi.SetValue(this, v);
                }

**Comment by jongoldDB** [comment]
This should now be enabled.
