### ISSUE TITLE
I believe --rp and --sp on Ambrosia RegisterInstance should be renamed

### ISSUE THREAD

**Issue by rrnewton** [microsoft/AMBROSIA#15]
After running these commands a million times, we take them for granted.  But I ran into trouble trying to explain this in the documentation:

    Ambrosia RegisterInstance -i myclient --rp 2000 --sp 2001 -l locallogs

Here's what they CLI help message says:

```
Usage: dotnet Ambrosia.dll RegisterInstance [OPTIONS]
Options:
  -i, --instanceName=VALUE   The instance name [REQUIRED].
      --rp, --receivePort=VALUE
                             The service receive from port [REQUIRED].
      --sp, --sendPort=VALUE The service send to port. [REQUIRED]
```

This phrasing is not clear -- "The service receive from port".  What does that mean?  _From_ what and _to_ what?

It seems that for RegisterInstance --rp/--sp are take the **perspective of the coordinator**.
Yet the user shouldn't really have to think about the ImmortalCoordinator, instead they think about their own application. 

Then, if you call something like PerfTestInterruptible Client/Server the arguments are flipped, all of a sudden and --rp/--sp are reversed (same argument flags, but different meaning, or shifted to the perspective of the app).

It would be waaay better to call these `--toCoord`/`--tc` and `--fromCoord`/`--fc`, which does not leave room for confusion.  Of course, when building a client for the wire protocol one has to know which port connects and which port accepts (_sender_ connects convention for each direction of traffic).

**Comment by nlebeck** [comment]
+1 on this, and I think it's important to make this a broad and consistent change given that these terms pop up in other places as well. I ran into the same problems when I was working on the documentation.
