### ISSUE TITLE
Question: How is this different from Orleans?

### ISSUE THREAD

**Issue by Narvalex** [Microsoft/AMBROSIA#17]
Both are actor model frameworks... how is this different?

**Comment by rrnewton** [comment]
@sebastianburckhardt can provide a more full answer, as one of the original Orleans developers.

In short, traditional actor models (Erlang, etc) provide helpful mechanisms for the programmer to respond to failure, but they don't attempt to *hide* failure from the programming model.  In contrast, in AMBROSIA, one simply programs as though machines *never* fail [1].  The underlying runtime maintains this illusion by replication, checkpointing, logging, replaying, etc.

Thus, in AMBROSIA, an int64 field of an object sitting in memory is just as "safe" as data sitting on disk in a database.  One can write stateful services fearlessly (and without the *cost* of always fetching and returning data to persistent storage as a stateless serverless function needs to do).

[1] Just like MPI *assumes* -- but MPI does not maintain this programming abstraction in the face of physical hardware failure, AMBROSIA does.

**Comment by darrenge** [comment]
There is a bit of info on Gitter …
https://gitter.im/AMBROSIA-resilient-systems/Lobby#utm_source=notification&utm_medium=email&utm_campaign=unread-notifications

We are working on a more comprehensive explanation on the Orleans questions which will be ready in a couple days

**Comment by Narvalex** [comment]
>           We now have a more detailed comparison with Orleans checked into GitHub. It is accessible from the root readme :)

Thanks!

**Comment by NickDarvey** [comment]
Hi @jongoldDB, why was the Orleans comparison reverted?
