### ISSUE TITLE
AmbrosiaCS.exe crashes due to missing AmbrosiaLibCS DLL in 1.0.1.0 Windows release

### ISSUE THREAD

**Issue by nlebeck** [Microsoft/AMBROSIA#47]
When I run the version of `AmbrosiaCS.exe` included in the 1.0.1.0 Windows binary release, it crashes with the following exception:

    Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'AmbrosiaLibCS, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
       at Ambrosia.Utilities.GetMethodInformation(MethodInfo m, UInt32 i)
       at System.Linq.Enumerable.<SelectIterator>d__5`2.MoveNext()
       at Ambrosia.ProxyInterfaceGenerator.TransformText()
       at Ambrosia.Program.RunCodeGen()
       at Ambrosia.Program.Main(String[] args)

It looks like the problem is that the `AmbrosiaLibCS.dll` file is not included in the 1.0.1.0 Windows ZIP file, whereas that DLL was included in the previous releases. I think this particular crash is because the codegen program is trying to use the `ImpulseHandlerAttribute` type defined in `AmbrosiaLibCS`.

**Comment by darrenge** [comment]
You are right … AmbrosiaLibCS.dll was not in this zip file.  I updated the zip file in the release so it is there now.  Thanks for reporting.
