### ISSUE TITLE
AmbrosioaCS Codegen not running on dotnet core build - XML parse error

### ISSUE THREAD

**Issue by rrnewton** [Microsoft/AMBROSIA#5]
It gives this error:

```
root@585edf0692a3:/ambrosia/InternalImmortals/PerformanceTestInterruptible# 
$ AmbrosiaCS CodeGen -a IJob/bin/Release/netcoreapp2.0/linux-x64/IJob.dll -a API/bin/Release/netcoreapp2.0/linux-x64/ServerAPI.dll -o PTIAmbrosiaGeneratedAPI -f netcoreapp2.0 -b ./CodeGenDependencies/netcoreapp2.0/

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'Microsoft.CodeAnalysis, Version=2.7.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Ambrosia.Program.RunCodeGen()
   at Ambrosia.Program.Main(String[] args) in /ambrosia/Clients/CSharp/AmbrosiaCS/Program.cs:line 32
Aborted
```

2.7 is referred to in our top level nuspec:

```
Ambrosia.nuspec:      <dependency id="Microsoft.CodeAnalysis.CSharp.Scripting" version="2.7.0" />
```

I don't really know how that's used but I'm guessing it's only for building a nuget package, not for our `dotnet publish`-based scripted builds.  The directory we publish to (`bin` within the working directory, or `/ambrosia/bin` within the Docker containers) ends up with a copy of the 2.6 DLL not the 2.7 one.

@jongoldDB mentioned that something actually needed a specific (2.6 or 2.7) version of this library and that @mike-barnett may know something about it?

@darrenge  - this is the blocking bug that is keeping Linux CI from working on Master.  (`ryan/temp` branch only works because it is held back against an older version of the codegen, and therefore missing the changes that cause this breakage, whatever those were.)

**Comment by rrnewton** [comment]
Ok, after commit 2bfec9b4df223f13b4e385d61f9e8c3ff7e4b54b, we get a different error (perhaps we get further):

```bash
root@103f75a2dfeb:/ambrosia/InternalImmortals/PerformanceTestInterruptible# AmbrosiaCS CodeGen -a IJob/bin/Release/netcoreapp2.0/linux-x64/IJob.dll -a API/bin/Release/netcoreapp2.0/linux-x64/ServerAPI.dll -o PTIAmbrosiaGeneratedAPINetCore -f netcoreapp2.0 -b ./CodeGenDependencies/netcoreapp2.0

Unhandled Exception: System.Xml.XmlException: Data at the root level is invalid. Line 1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Parse(String text, LoadOptions options)
   at Ambrosia.Program.RunCodeGen() in /ambrosia/Clients/CSharp/AmbrosiaCS/Program.cs:line 161
   at Ambrosia.Program.Main(String[] args) in /ambrosia/Clients/CSharp/AmbrosiaCS/Program.cs:line 32
```

It comes from this line of code in the Codegen:

```C#
            var doc = XDocument.Parse(Resources.AmbrosiaCS);
```

Any ideas on this one @jongoldDB, @TalZaccai, @mike-barnett ?

**Comment by rrnewton** [comment]
A full reproducer for that XML exception can be found in this build:
https://msrfranklin.visualstudio.com/Franklin/_build/results?buildId=920
Reproduce locally by checkout it out and running `Scripts/run_windows_ci.sh`.

**Comment by TalZaccai** [comment]
Fixed in PR: https://github.com/Microsoft/AMBROSIA/pull/6
