### ISSUE TITLE
Real-time distributed server for multiplayer game like Halo w/ Orleans

### ISSUE THREAD

**Issue by RomanZhu** [microsoft/AMBROSIA#53]
How suitable that project for games/simulations?

How the Immortals concept fits the real-time game's data?

**Comment by jongoldDB** [comment]
Ambrosia could be a very good fit for video games. In particular, it would automatically heal connections and provide high availability for servers through active standbys. Finally, for multiplayer games with centralized servers, Ambrosia would, by its nature, serialize all requests to the server, which would help with conflict resolution between player actions. It is important, though, to consider latency, where it may or may not be ok depending on your target. Ambrosia's resiliency features come at the cost of a round trip to one of azure's storage options. We measured this at between 5-10 ms depending on the replicated storage option you choose. It is worth saying though, that ANY solution which is fully resilient to failure will incur at least this level of latency, and most solutions are significantly worse.

**Comment by jongoldDB** [comment]
Commented on in gitter
