### ISSUE TITLE
HelloWorld doc suggestion

### ISSUE THREAD

**Issue by lovettchris** [microsoft/AMBROSIA#66]
Pulled my hair out on the "dotnet Ambrosia.dll RegisterInstance -i=server -rp=2000 -sp=2001 -l=C:\logs\" getting "The CRA instance appears to be down. Restart it and this vertex will be instantiated automatically" until I realized the next paragraph says this is expected.  

I would have seen it if you put the expected error in triple back tick code block.

**Comment by cmeiklejohn** [comment]
I can submit a PR to revise this -- when I first used Ambrosia I also found this confusion as well.

**Comment by cmeiklejohn** [comment]
Addressed by https://github.com/microsoft/AMBROSIA/pull/67.

**Comment by lovettchris** [comment]
cool thanks!
