### ISSUE TITLE
Dynamic Port allocation

### ISSUE THREAD

**Issue by lovettchris** [microsoft/AMBROSIA#87]
CRA already provides CRA.ClientLibrary.NetworkUtils.GetAvailablePort(), so can the ImmortalCoordinator use that instead of requiring user to come up with valid port numbers?

**Comment by jongoldDB** [comment]
The problem is that when 2 separate processes are used, both have to use the same ports, so the port would need to be communicated from the ImmortalCoordinator to the language binding, which requires use of an agreed on port...
